# Imports

In [30]:
import pandas as pd
import os

## Load Carbon Intensity datasets

In [31]:
# base path
base_path = "../data/raw/"
years = [2021, 2022, 2023]  

# Read
df_CI_hourly = pd.concat([pd.read_csv(f"{base_path}CH_{year}_hourly.csv") for year in years], ignore_index=True)

### relative path to be written to an excel file

In [32]:
relative_path = os.path.join("..", "data", "preprocessed", "processed_data.xlsx")

## Load energy consumption and production dataset

In [33]:
path="../data/raw/"

df_energy = pd.concat([pd.read_excel(f"{path}EnergieUebersichtCH-{year}.xlsx",sheet_name='Zeitreihen0h15') for year in years], ignore_index=True)

# Dataset Information

check the loaded datasets

In [34]:
# carbon intensity
df_CI_hourly.head()

,Datetime (UTC),Country,Zone Name,Zone Id,Carbon Intensity gCO₂eq/kWh (direct),Carbon Intensity gCO₂eq/kWh (LCA),Low Carbon Percentage,Renewable Percentage,Data Source,Data Estimated,Data Estimation Method
0,01/01/2021 00:00,Switzerland,Switzerland,CH,147.82,187.06,80.25,35.14,Electricity Maps Estimation,True,ESTIMATED_MODE_BREAKDOWN
1,01/01/2021 01:00,Switzerland,Switzerland,CH,159.56,199.85,78.84,33.17,Electricity Maps Estimation,True,ESTIMATED_MODE_BREAKDOWN
2,01/01/2021 02:00,Switzerland,Switzerland,CH,140.89,179.60,80.34,33.88,Electricity Maps Estimation,True,ESTIMATED_MODE_BREAKDOWN
3,01/01/2021 03:00,Switzerland,Switzerland,CH,122.40,159.06,81.49,30.38,Electricity Maps Estimation,True,ESTIMATED_MODE_BREAKDOWN
4,01/01/2021 04:00,Switzerland,Switzerland,CH,142.60,180.92,80.02,30.54,Electricity Maps Estimation,True,ESTIMATED_MODE_BREAKDOWN

In [35]:
# consumption and production
df_energy.head()

,Unnamed: 0,Summe endverbrauchte Energie Regelblock Schweiz\nTotal energy consumed by end users in the Swiss controlblock,Summe produzierte Energie Regelblock Schweiz\nTotal energy production Swiss controlblock,Summe verbrauchte Energie Regelblock Schweiz\nTotal energy consumption Swiss controlblock,Netto Ausspeisung aus dem Übertragungsnetz Schweiz\nNet outflow of the Swiss transmission grid,Vertikale Einspeisung ins Übertragungsnetz Schweiz\nGrid feed-in Swiss transmission grid,Positive Sekundär-Regelenergie\nPositive secundary control energy,Negative Sekundär-Regelenergie\nNegative secundary control energy,Positive Tertiär-Regelenergie\nPositive tertiary control energy,Negative Tertiär-Regelenergie\nNegative tertiary control energy,...,"Produktion Kantone OW, NW, UR\nProduction Cantons OW, NW, UR","Verbrauch Kantone OW, NW, UR\nConsumption Cantons OW, NW, UR","Produktion Kantone GE, VD\nProduction Cantons GE, VD","Verbrauch Kantone GE, VD\nConsumption Cantons GE, VD","Produktion Kantone SH, ZH\nProduction Cantons SH, ZH","Verbrauch Kantone SH, ZH\nConsumption Cantons SH, ZH",Produktion Kantonsübergreifend\nProduction across Cantons,Verbrauch Kantonsübergreifend\nConsumption across Cantons,Produktion Regelzone CH - Ausländische Gebiete\nProduction control area CH - foreign territories,Verbrauch Regelzone CH - Ausländische Gebiete\nConsumption control area CH - foreign territories
0,Zeitstempel,kWh,kWh,kWh,kWh,kWh,kWh,kWh,kWh,kWh,...,kWh,kWh,kWh,kWh,kWh,kWh,kWh,kWh,kWh,kWh
1,01.01.2021 00:15,1671630.088625,1210856.088,1880710.202024,635189.489912,869233.8751,17242,-2392,0,0,...,9768.566,32685.315,27109.446,260040.413,20405.967,278109.595,97665.574,39143.313088,866.686,13374.112
2,01.01.2021 00:30,1661251.405625,1192987.411,1877758.191115,647088.60469,863927.1974,2639,-431,0,0,...,9764.704,32658.413,24469.448,260521.051,20517.589,277796.491,97445.697,42522.34031,822.455,13178.706
3,01.01.2021 00:45,1641591.90225,1194179.748,1854953.225189,625842.285412,864593.4948,230,-574,0,0,...,9181.536,32633.269,23613.422,257754.89,20614.251,273597.39,97301.079,39361.129588,615.664,12764.405
4,01.01.2021 01:00,1627956.774625,1188029.012,1847096.580761,621354.563153,857114.1599,126,-2521,0,0,...,6632.47,31527.531,23336.463,255148.58,20454.126,269694.877,97292.006,41680.276847,618.147,12354.812

convert to date time, drop first row and reset index

In [36]:
#Rename column
df_energy.rename(columns={'Summe endverbrauchte Energie Regelblock Schweiz\nTotal energy consumed by end users in the Swiss controlblock': 'End user energy consumtion(KWH)', 
                   'Summe produzierte Energie Regelblock Schweiz\nTotal energy production Swiss controlblock': 'Total energy production Swiss controlblock(KWH)',
                    'Summe verbrauchte Energie Regelblock Schweiz\nTotal energy consumption Swiss controlblock':'Total energy consumption Swiss controlblock(KWH)',
                    'Vertikale Einspeisung ins Übertragungsnetz Schweiz\nGrid feed-in Swiss transmission grid':'Grid feed-in Swiss transmission grid(KWH)',
                    'Netto Ausspeisung aus dem Übertragungsnetz Schweiz\nNet outflow of the Swiss transmission grid':'Net outflow of the Swiss transmission grid(KWH)'}, inplace=True)

In [37]:
# rename
df_CI_hourly.rename(columns={'Datetime (UTC)':'Date'},inplace=True)
df_CI_hourly['Date']=pd.to_datetime(df_CI_hourly['Date'],dayfirst=True)
#set index
df_CI_hourly.set_index('Date',inplace=True)

In [38]:
df_CI_hourly.head()

,Country,Zone Name,Zone Id,Carbon Intensity gCO₂eq/kWh (direct),Carbon Intensity gCO₂eq/kWh (LCA),Low Carbon Percentage,Renewable Percentage,Data Source,Data Estimated,Data Estimation Method
Date,,,,,,,,,,
2021-01-01 00:00:00,Switzerland,Switzerland,CH,147.82,187.06,80.25,35.14,Electricity Maps Estimation,True,ESTIMATED_MODE_BREAKDOWN
2021-01-01 01:00:00,Switzerland,Switzerland,CH,159.56,199.85,78.84,33.17,Electricity Maps Estimation,True,ESTIMATED_MODE_BREAKDOWN
2021-01-01 02:00:00,Switzerland,Switzerland,CH,140.89,179.60,80.34,33.88,Electricity Maps Estimation,True,ESTIMATED_MODE_BREAKDOWN
2021-01-01 03:00:00,Switzerland,Switzerland,CH,122.40,159.06,81.49,30.38,Electricity Maps Estimation,True,ESTIMATED_MODE_BREAKDOWN
2021-01-01 04:00:00,Switzerland,Switzerland,CH,142.60,180.92,80.02,30.54,Electricity Maps Estimation,True,ESTIMATED_MODE_BREAKDOWN

rename and drop unnecesary row

In [39]:
df_energy.rename(columns={'Unnamed: 0':'Date'},inplace=True)
df_energy=df_energy.drop(index=0)
df_energy.reset_index(drop=True,inplace=True)
df_energy['Date']=pd.to_datetime(df_energy['Date'],errors='coerce',dayfirst=True)
df_energy.set_index('Date',inplace=True)

In [44]:
df_energy.head()

,End user energy consumtion(KWH),Total energy production Swiss controlblock(KWH),Total energy consumption Swiss controlblock(KWH),Net outflow of the Swiss transmission grid(KWH),Grid feed-in Swiss transmission grid(KWH),Positive Sekundär-Regelenergie\nPositive secundary control energy,Negative Sekundär-Regelenergie\nNegative secundary control energy,Positive Tertiär-Regelenergie\nPositive tertiary control energy,Negative Tertiär-Regelenergie\nNegative tertiary control energy,Verbundaustausch CH->AT\nCross Border Exchange CH->AT,...,"Produktion Kantone OW, NW, UR\nProduction Cantons OW, NW, UR","Verbrauch Kantone OW, NW, UR\nConsumption Cantons OW, NW, UR","Produktion Kantone GE, VD\nProduction Cantons GE, VD","Verbrauch Kantone GE, VD\nConsumption Cantons GE, VD","Produktion Kantone SH, ZH\nProduction Cantons SH, ZH","Verbrauch Kantone SH, ZH\nConsumption Cantons SH, ZH",Produktion Kantonsübergreifend\nProduction across Cantons,Verbrauch Kantonsübergreifend\nConsumption across Cantons,Produktion Regelzone CH - Ausländische Gebiete\nProduction control area CH - foreign territories,Verbrauch Regelzone CH - Ausländische Gebiete\nConsumption control area CH - foreign territories
Date,,,,,,,,,,,,,,,,,,,,,
2021-01-01 00:15:00,1671630.088625,1210856.088,1880710.202024,635189.489912,869233.8751,17242,-2392,0,0,0,...,9768.566,32685.315,27109.446,260040.413,20405.967,278109.595,97665.574,39143.313088,866.686,13374.112
2021-01-01 00:30:00,1661251.405625,1192987.411,1877758.191115,647088.60469,863927.1974,2639,-431,0,0,0,...,9764.704,32658.413,24469.448,260521.051,20517.589,277796.491,97445.697,42522.34031,822.455,13178.706
2021-01-01 00:45:00,1641591.90225,1194179.748,1854953.225189,625842.285412,864593.4948,230,-574,0,0,0,...,9181.536,32633.269,23613.422,257754.89,20614.251,273597.39,97301.079,39361.129588,615.664,12764.405
2021-01-01 01:00:00,1627956.774625,1188029.012,1847096.580761,621354.563153,857114.1599,126,-2521,0,0,0,...,6632.47,31527.531,23336.463,255148.58,20454.126,269694.877,97292.006,41680.276847,618.147,12354.812
2021-01-01 01:15:00,1654789.95175,1233025.852,1901830.189312,631406.874869,888966.8143,31172,-5,0,0,0,...,5993.125,32705.948,23221.131,260324.195,20595.143,265106.105,96116.856,40607.110131,560.224,12427.88

resample 15min data to hourly data

In [40]:

# resample the columns needed and aggregate them
df_energy_hourly = df_energy.resample('h').agg({
    'End user energy consumtion(KWH)': 'sum',  
    'Total energy production Swiss controlblock(KWH)' :'sum',
    'Total energy consumption Swiss controlblock(KWH)': 'sum',
    'Grid feed-in Swiss transmission grid(KWH)':'sum',
    'Net outflow of the Swiss transmission grid(KWH)': 'sum'  
})

keep the CI to merge

In [41]:
df_CI_tomerge=df_CI_hourly[['Carbon Intensity gCO₂eq/kWh (LCA)','Carbon Intensity gCO₂eq/kWh (direct)','Low Carbon Percentage','Renewable Percentage']]

## merge the two datasets

In [42]:
df=pd.merge(df_CI_tomerge,df_energy_hourly,on='Date')

Write to an excel file

In [43]:
df.to_excel(relative_path, index=True)